# Run: conda env update --file environment.yml -n sagemaker-distribution
channels:
  - conda-forge
dependencies:
  - conda
  - docker-py
  - pip45
  - boto3
  - pytestw
  - pytest-mock
  - pytest-xdist
  - semver
  - autoflake
  - black1
  - isort3
  - pre-commit
